# Generated by Django 3.2.25 on 2024-05-02 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_album_date_added'),
        ('user_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_wishlist.userwishlist')),
            ],
        ),
    ]
