# Generated by Django 5.0.6 on 2024-06-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationpost',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
