# Generated by Django 3.2.25 on 2024-05-04 10:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_album_date_added'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendation',
            new_name='RecommendationPost',
        ),
    ]
