# Generated by Django 3.2.25 on 2024-05-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_recommendation_recommendationpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationpost',
            name='artist',
        ),
        migrations.AlterField(
            model_name='recommendationpost',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
