# Generated by Django 5.0.6 on 2024-06-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='discount',
        ),
    ]
