# Generated by Django 3.2.25 on 2024-04-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20240417_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
